version: '3'
services:
  piweb:
    image: piweb:latest
    container_name: "piweb"
    build:
      context: web
      dockerfile: Dockerfile
    links:
      - flaskweb #:db1.prod.ability.com
    ports:
      - 80:8080
    expose:
      - 8080
    depends_on:
      - flaskweb
    tty: true
    command: python /pi_server.py
  flaskweb:
    image: flaskweb:latest
    container_name: "flaskweb"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    command: python /app/main.py
    tty: true
